/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.synechron.enbd.creditcard.enbdcreditcard.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SchemaAccount extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1629106792405912553L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SchemaAccount\",\"namespace\":\"com.synechron.enbd.creditcard.enbdcreditcard.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"int\",\"default\":0},{\"name\":\"name\",\"type\":\"string\",\"default\":\"string\"},{\"name\":\"totalBalance\",\"type\":\"double\",\"default\":0.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SchemaAccount> ENCODER =
      new BinaryMessageEncoder<SchemaAccount>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SchemaAccount> DECODER =
      new BinaryMessageDecoder<SchemaAccount>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SchemaAccount> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SchemaAccount> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SchemaAccount>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SchemaAccount to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SchemaAccount from a ByteBuffer. */
  public static SchemaAccount fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public double totalBalance;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SchemaAccount() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param totalBalance The new value for totalBalance
   */
  public SchemaAccount(java.lang.Integer id, java.lang.CharSequence name, java.lang.Double totalBalance) {
    this.id = id;
    this.name = name;
    this.totalBalance = totalBalance;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return totalBalance;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: totalBalance = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'totalBalance' field.
   * @return The value of the 'totalBalance' field.
   */
  public java.lang.Double getTotalBalance() {
    return totalBalance;
  }

  /**
   * Sets the value of the 'totalBalance' field.
   * @param value the value to set.
   */
  public void setTotalBalance(java.lang.Double value) {
    this.totalBalance = value;
  }

  /**
   * Creates a new SchemaAccount RecordBuilder.
   * @return A new SchemaAccount RecordBuilder
   */
  public static com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder newBuilder() {
    return new com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder();
  }

  /**
   * Creates a new SchemaAccount RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SchemaAccount RecordBuilder
   */
  public static com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder newBuilder(com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder other) {
    return new com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder(other);
  }

  /**
   * Creates a new SchemaAccount RecordBuilder by copying an existing SchemaAccount instance.
   * @param other The existing instance to copy.
   * @return A new SchemaAccount RecordBuilder
   */
  public static com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder newBuilder(com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount other) {
    return new com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder(other);
  }

  /**
   * RecordBuilder for SchemaAccount instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SchemaAccount>
    implements org.apache.avro.data.RecordBuilder<SchemaAccount> {

    private int id;
    private java.lang.CharSequence name;
    private double totalBalance;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.totalBalance)) {
        this.totalBalance = data().deepCopy(fields()[2].schema(), other.totalBalance);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SchemaAccount instance
     * @param other The existing instance to copy.
     */
    private Builder(com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.totalBalance)) {
        this.totalBalance = data().deepCopy(fields()[2].schema(), other.totalBalance);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalBalance' field.
      * @return The value.
      */
    public java.lang.Double getTotalBalance() {
      return totalBalance;
    }

    /**
      * Sets the value of the 'totalBalance' field.
      * @param value The value of 'totalBalance'.
      * @return This builder.
      */
    public com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder setTotalBalance(double value) {
      validate(fields()[2], value);
      this.totalBalance = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'totalBalance' field has been set.
      * @return True if the 'totalBalance' field has been set, false otherwise.
      */
    public boolean hasTotalBalance() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'totalBalance' field.
      * @return This builder.
      */
    public com.synechron.enbd.creditcard.enbdcreditcard.schema.SchemaAccount.Builder clearTotalBalance() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SchemaAccount build() {
      try {
        SchemaAccount record = new SchemaAccount();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.totalBalance = fieldSetFlags()[2] ? this.totalBalance : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SchemaAccount>
    WRITER$ = (org.apache.avro.io.DatumWriter<SchemaAccount>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SchemaAccount>
    READER$ = (org.apache.avro.io.DatumReader<SchemaAccount>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
